const mongoose = require('mongoose');

const bookingSchema = mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    villa: { type: mongoose.Schema.Types.ObjectId, ref: 'Villa', required: true },
    checkIn: { type: Date, required: [true, 'Please add check-in date'] },
    checkOut: { type: Date, required: [true, 'Please add check-out date'] },
    nights: { type: Number, default: 0 },
    guests: { type: Number, required: true, default: 1 },
    adults: { type: Number, default: 1 },
    kids: { type: Number, default: 0 },
    infants: { type: Number, default: 0 },
    pets: { type: Number, default: 0 },
    totalPrice: { type: Number, required: true },
    estimatedPrice: { type: Number },
    status: {
      type: String,
      enum: ['pending', 'pending-custom', 'confirmed', 'rejected', 'cancelled', 'completed'],
      default: 'pending',
    },
    customerName: { type: String },
    customerEmail: { type: String },
    customerPhone: { type: String },
    customerCountry: { type: String },
    purposeOfStay: { type: String },
    arrivalTime: { type: String },
    specialRequests: { type: String },
    paymentMethod: { type: String, default: 'pending' },
    standardCapacity: { type: Number },
    requestedGuests: { type: Number },
    extraGuests: { type: Number },
    isCustomBooking: { type: Boolean, default: false },
    requiresManualReview: { type: Boolean, default: false },
    approvalReason: { type: String },
    internalNotes: { type: String },
    offerSent: { type: Boolean, default: false },
    customPricing: {
      basePrice: { type: Number },
      extraGuestFee: { type: Number, default: 0 },
      extraGuestCount: { type: Number, default: 0 },
      cleaningFee: { type: Number, default: 0 },
      additionalServices: { type: Number, default: 0 },
      housekeepingCharges: { type: Number, default: 0 },
      beddingCharges: { type: Number, default: 0 },
      securityCharges: { type: Number, default: 0 },
      transportation: { type: Number, default: 0 },
      chefServices: { type: Number, default: 0 },
      decoration: { type: Number, default: 0 },
      airportPickup: { type: Number, default: 0 },
      discount: { type: Number, default: 0 },
      complimentaryServices: { type: String, default: '' },
      overrideAmount: { type: Number },
      totalPerNight: { type: Number },
      totalAmount: { type: Number },
      offerMessage: { type: String },
      _id: false,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Booking', bookingSchema);
